ChefsTable/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ChefsTable_control.urls')),
    #path('api/', include('ChefsTable_APIs.urls')),
]

ChefsTable_control/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('form/', views.form_view),
    path('', views.home, name = "home"),
    path('about/', views.about, name="about"),
    path('menu/', views.menu, name = "menu"),
    path('booking/', views.reservation, name = "booking"),

]

ChefsTable_APIs/models.py
from django.db import models

# Create your models here.

ChefsTable_control/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Inputf(models.Model):
    Name = models.CharField(max_length=200)
    time_log = models.TimeField()

class Reservation(models.Model):
    name = models.CharField("Name",max_length=250)
    contact = models.CharField("Phone Number", max_length=200)
    reservation_date = models.DateField(default=timezone.now)
    reservation_slot = models.SmallIntegerField(default=10)
    count = models.IntegerField("Number of People", default=1)
    notes = models.CharField("Note", max_length=650)
    
    def __str__(self) -> str:
        return self.name


class Cuisine(models.Model):
    cusine = models.CharField(max_length=250)
    cusineid = models.IntegerField(primary_key=True,default=None)

    def __str__(self) -> str:
        return self.cusine

class Menu(models.Model):
    name = models.CharField(max_length=250)
    cusineid = models.ForeignKey(Cuisine, on_delete=models.PROTECT, default=None)
    price = models.IntegerField(null=False)
    description = models.CharField(max_length=750)
    
    def __str__(self) -> str:
        return self.name

ChefsTable_control/forms.py
from django import forms
from .models import Inputf, Reservation


class InputForm(forms.ModelForm):
    class Meta:
        model = Inputf
        fields = '__all__'
    
class Booking(forms.ModelForm):
    class Meta:
        model = Reservation
        fields ='__all__'

ChefsTable_APIs/views.py
from django.shortcuts import render

# Create your views here.

ChefsTable_control/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import InputForm, Booking
from .models import Cuisine, Menu
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.core import serializers
from django.utils import timezone
from rest_framework.views import APIView
from rest_framework.response import Response
from .models import Reservation
# Create your views here.

def form_view(request):
    form = InputForm()
    if request.method == "POST":
        form = InputForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("Reservation Success!")

    else :    
        context = {"form": form}
        return render(request, "booking.html", context)

@method_decorator(csrf_exempt, name='dispatch')
class BookingsView(APIView):
    def post(self, request, *args, **kwargs):
        data = request.data
        exist = Reservation.objects.filter(reservation_date=data['reservation_date']).filter(
            reservation_slot=data['reservation_slot']).exists()
        if not exist:
            booking = Reservation.objects.create(
                first_name=data['first_name'],
                reservation_date=data['reservation_date'],
                reservation_slot=data['reservation_slot'],
            )
            return Response({'success': True})
        else:
            return Response({'error': 'Booking already exists.'}, status=400)
        
    def get(self, request, *args, **kwargs):
        date = request.GET.get('date', timezone.now().date())
        bookings = Booking.objects.filter(reservation_date=date)
        booking_json = serializers.serialize('json', bookings)
        return Response(booking_json, content_type='application/json')


def home(request):
    return render(request,'home.html')


def about(request):
    #about_content = {'about' : "Order food online and get it delivered to you Hot and fresh at your doorstep!"}
    return render(request,"about.html")

def menu(request):
    cuisines = Cuisine.objects.all()
    menus = Menu.objects.all()
    context = {'cuisines': cuisines, 'menus': menus}
    return render(request, 'menu.html', context)

def reservation(request):
    form = Booking()
    if request.method == "POST":
        form = Booking(request.POST)
        if form.is_valid():
            form.save()
            return render(request,"sucessbook.html",{"form": form, 'successful_submit': False} )
        
    context = {"form": form, 'successful_submit': False}
    return render(request, "booking.html", context)

ChefsTable_control/templates/about.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section>
  <article>
    <h1>About Us</h1>
    <!--Begin row-->
    <div class="row">
      <!--Begin col-->
      <div class="column">
        <style>
            p{
                text-align: left;
                color:grey;
            }
        </style>
        
        <p>
            Based in London, United Kingdom ChefsTable is a family owned
            restaurant, focused mainly on traditional Indian recipes served with a
            modern twist. With our cuisines expanding from Indian to Itaian, mexican, chinese putting on an Indian twist to each of these cusines.
        </p>
        <p>
          A 7 star experience costing you as less as food from a food truck. We believe in giving the best experince to all our customer
          starting with our lounge, to the seating the view and the food. Food doesn't have to be fancy, it just has to be tasty enough so you can get
          through your day.
        </p>

        <p>
          The restaurant has several different looks with a rustic and relaxed atmosphere, to a classy modern 7 star hotel environment,
          making it a popular place for a meal any time of the day. You can have a classic cafe environment or a club environment whatever you are
          in the mood for.
        </p>

        <p>
          ChefsTable is owned by Nitin who built this restaurant solely for the purpose 
          of showing the world that food can be tasty and affordable by everyone.

        </p>
        <p>
            ChefsTable is an all vegetarian, non alcoholic restaurant. This was built considering the fact
            there are not many only vegetarian restaurants in the world. ChefsTable brings you the 7 star experience
            to an all vegetarian based cusine.
        </p>
        <p>
            <br>
        </p>
        <p>
            <br>
        </p>
        <p style="text-align: right;"> 
          Life is a combination of Food and Magic - Nitin
        </p>

    
      </div>
      <!--End col-->

    

      <!--Begin col-->
      <div class="column">
        <figure class="figure">
          <img
            src="{% static 'images/9.jpg' %}"
            alt="Mario and Adrian" style="width: 100%"
          />
          <figcaption class="figure-caption" style="text-align: center;">
            A peek at one of our dining areas.
          </figcaption>
        </figure>
      </div>
      <!--End col-->
    </div>
    <!--End row-->
  </article>
</section>
<style>
  p{
    margin: 0 20px 10px;
  }
  h1{
    margin: 0 5px 0;
  }
  main article {
    border: 7px solid #EDEFEE;
  }
</style>
{% endblock %}

ChefsTable_control/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ChefsTable</title>
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'images/logo2.png' %}"
    />
    <!-- Include your CSS files here -->
    <link
      rel="preload"
      as="style"
      href="{% static 'css/style.css' %}"
      onload="this.rel = 'stylesheet'"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Karla&family=Markazi+Text:wght@500&display=swap"
      rel="stylesheet"
    />
    <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    



</head>
<body>
    
    {% include 'partials/header.html' %}

    <main>{% block content %} {% endblock %}</main>

    {% include 'partials/footer.html' %}
</body>
</html>

ChefsTable_control/templates/booking.html
{% load static %}
<head>
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
	
	{% include 'partials/header.html' %}
{% block content %}
<section>
	
	<article>
	  <h1>Make a reservation</h1>
	  <!--Begin row-->
	  <div class="row">
		<!--Begin col-->
		<div class="column">
		  <form action="" method="post">
			{% csrf_token %}
			<style>
				p{
					text-align: left;
				}
			</style>
			{{form.as_p}}
			<input type="submit" id="button">
		  </form>
		</div>
		<!--End col-->
  
		<!--Begin col-->
		<figure class="room-box"> <img src="{% static 'images/1.jpeg' %}" alt="Image" width="100%">
          
        </figure>
		<!--End col-->
	  </div>
	  <!--End row-->
  
  
  
  
	</article>
  </section>
</body>
  {% include 'partials/footer.html' %}s
{% endblock %}

ChefsTable_control/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link href="{% static 'css/style.css' %}" rel="stylesheet">


<body>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<section>
    <article id="hero">
      
      <h1 class="heading_shadow">SPECIAL OFFER</h1>
      <p>
        Don't have a seat reserved for you after booking ? The food is on the house.
      </p>
      <a href="{% url 'booking' %}" class="cta"> Book now </a>
    </article>
</section>
<section class="highlight-rooms">
  
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          
          <h3 style="text-align: center; margin-bottom: 0px; color: #d0a043;">ChefsTable</h2>
          <h2 style="font-size: 30px; margin-bottom: 0px; text-align: center; line-height: 1.2;"> Elegant, Classy, Luxurious and on top of all Affordable. </h2>
          <p class="lead" style="text-align: center;">  A high class restaurant for all vegetarian's with a wide variety of cuisines to appetize yourself with. The look of a classy stylish restaurant at the price of a normal food truck. With prices starting as low as £5 and the costliest item being £100 we have it all. You name it and we'll have it.</p>
  
          <div style="text-align: center;">
  
           <a href="{% url 'about' %}" class="button"><span data-hover="KNOW MORE">KNOW MORE</span></a>
           <style>
            .highlight-rooms{ width: 100%; float: left; padding: 100px 0;}
            .highlight-rooms h2{font-family: 'Playfair Display', serif; font-size: 60px; margin-bottom: 80px; margin-left: -5px; color: #192033;}
            .highlight-rooms h5{font-family: 'Playfair Display', serif; color: #999; margin-top: 15%;}
            .highlight-rooms h5:before{content: ""; width: 100px; height: 1px; float: left; background: #999; margin-top: 7px; margin-right: 7px;}
            .highlight-rooms .button{ height: 45px; line-height: 45px; display: inline-block; border: 1px solid #d0a043; background-color: #d0a043; padding: 0 30px; color: #fff; font-family: 'Playfair Display', serif; box-shadow: 10px 10px 30px rgba(0,0,0,0.05); overflow: hidden;}
            .highlight-rooms .button *{-webkit-transition: .25s ease-in-out;-moz-transition: .25s ease-in-out;-ms-transition: .25s ease-in-out; -o-transition: .25s ease-in-out; transition: .25s ease-in-out;}
            .highlight-rooms .button span { position: relative; display: inline-block;}
            .highlight-rooms .button span:before {position: absolute;top: 100%; content: attr(data-hover); }
            .highlight-rooms .button span:before {-webkit-transform: translate3d(0,0,0);-moz-transform: translate3d(0,0,0);transform: translate3d(0,0,0);}
            .highlight-rooms .button:hover span{-webkit-transform: translateY(-100%);-moz-transform: translateY(-100%);transform: translateY(-100%);}
            .highlight-rooms .room-box{ width: 100%; float: left;}
            .highlight-rooms .room-box img{ width: 100%; opacity: 0.5;}
            .highlight-rooms .room-box .room-details{ width: 100%; height: 0; float: left; margin-top: -90px; overflow: hidden; position: relative; padding: 0; color: #fff;}
            .highlight-rooms .room-box .room-details .room-name{font-family: 'Playfair Display', serif; color: #fff; font-size: 37px; margin-top: 0;}
            .highlight-rooms .room-box .room-details .room-desc{ width: 100%; float: left; font-family: 'Playfair Display', serif; text-transform: uppercase; color: #fff; margin-bottom: 10px; opacity: 0.4;}
            .highlight-rooms .room-box .room-details .room-price{ width: 100%; float: left; text-align: right; font-size: 40px;}
            .highlight-rooms .room-box .room-details .room-price small{ font-size: 17px;}
            .highlight-rooms .room-box .room-details .room-price span{ width: 100%; float: left; font-size: 10px; margin-top: -10px;}
            .highlight-rooms .room-box .room-details .room-button{ height: 50px; line-height: 50px; display: inline-block; border: 1px solid #ccc; padding: 0 40px; color: #999; font-family: 'Playfair Display', serif; box-shadow: 10px 10px 30px rgba(0,0,0,0.05); overflow: hidden;}
            .highlight-rooms .room-box .room-details .room-button *{-webkit-transition: .25s ease-in-out;-moz-transition: .25s ease-in-out;-ms-transition: .25s ease-in-out; -o-transition: .25s ease-in-out; transition: .25s ease-in-out;}
            .highlight-rooms .room-box .room-details .room-button span { position: relative; display: inline-block;}
            .highlight-rooms .room-box .room-details .room-button span:before {position: absolute;top: 100%; content: attr(data-hover); }
            .highlight-rooms .room-box .room-details .room-button span:before {-webkit-transform: translate3d(0,0,0);-moz-transform: translate3d(0,0,0);transform: translate3d(0,0,0);}
            .highlight-rooms .room-box .room-details .room-button:hover span{-webkit-transform: translateY(-100%);-moz-transform: translateY(-100%);transform: translateY(-100%); color: #fff;} 
            .highlight-rooms .center { z-index: 2;} 
            .highlight-rooms .center .room-box{width: 120%; margin-left: -10%; margin-top: -50px; box-shadow: 10px 10px 30px rgba(0,0,0,0.15);}
            .highlight-rooms .center .room-box img{opacity: 1;}
            .highlight-rooms .center .room-box .room-details{ height: auto; margin-top: -186px; background: #1c1b21; padding: 20px 25px;}
            .highlight-rooms .owl-item{padding:30px 0; }
            .highlight-rooms .owl-dots{ width: 100%; float: left; text-align: center;}
            .highlight-rooms .owl-dots .owl-dot{ width: 16px; height: 3px; display: inline-block; background: #ccc; margin: 0 2px;}
            .highlight-rooms .owl-dots .owl-dot.active{width: 36px; background: #000;}</style>
  
          </div>
        </div>
        <!-- end col-4 -->
  <div class="col-md-8">
    <div class="owl-carousel">
      <div class="owl-item">
        <figure class="room-box"> <img src="{% static 'images/1.jpeg' %}" alt="Image">
          
        </figure>
        <!-- end room-box --> 
      </div>
      <!-- end owl-item -->
      <div class="owl-item">
        <figure class="room-box"> <img src="{% static 'images/2.jpeg' %}" alt="Image">
          <p style="position: center; top: 300%; bottom: 100%; text-align: center; font-size: 1.75rem;">
      
            Reserve your table for the most amazing dining experience. Have a seating preference ? No problem just let us know what you'd like to experience and we will do our best to ensure you get the experience you've expected.
          
          <p>
            <a href="{% url 'booking' %}" style="text-align: center;">Book your table now</a>
        </figure>
        <!-- end room-box --> 
      </div>
      <!-- end owl-item -->
      <div class="owl-item">
        <figure class="room-box"> <img src="{% static 'images/4.jpeg' %}" alt="Image">
        </figure>
        <!-- end room-box --> 
      </div>
      <div class="owl-item">
        <figure class="room-box"> <img src="{% static 'images/5.jpg' %}" alt="Image">
          <p style="position: center; top: 300%; bottom: 100%; text-align: center; font-size: 1.75rem;">
              Our premium lounge, everything in it is free of cost, Until you get a seat. So sit down and relax in a 5 star environment. 
          <p>
        </figure>
        <!-- end room-box --> 
      </div>
      <div class="owl-item">
        <figure class="room-box"> <img src="{% static 'images/7.jpg' %}" alt="Image">
          
        </figure>
        <!-- end room-box --> 
      </div>
      <!--end owl-item -->
      <div class="owl-item">
        <figure class="room-box"> <img src="{% static 'images/10.jpg' %}" alt="Image">
          <p>
            Our menu consists cuisines from around the world. To name a few Italian, Mexican, Indian and many more!!!
          </p>
          <p>
            <a href="{% url 'menu' %}">See our new menu</a>
          </p>
        </figure>
        <!-- end room-box --> 
      </div>
      <!-- end owl-item -->
    </div>
   <!-- end owl-carousel --> 
  </div>
  <!-- end col-8 --> 
</div>
<!-- end row --> 
</div>
<!-- end container --> 
</section>




<script src="{% static 'js/bootstrap.min.js' %}"></script> 


<script src="{% static 'js/owl.carousel.min.js' %}"></script> 

<script src="{% static 'js/jquery.fancybox.js' %}"></script> 

<script src="{% static 'js/jquery.stellar.js' %}"></script> 

<script src="{% static 'js/isotope.js' %}"></script> 

<script src="{% static 'js/odometer.min.js' %}"></script> 

<script src="{% static 'js/scripts.js' %}"></script> 

</body>
{% endblock %}

ChefsTable_control/templates/indian.html
<div class="tabs-content">
    {% for cuisine in cuisines %}
        <section id="{{ cuisine.cusine|slugify }}" role="tabpanel" aria-labelledby="tab-{{ cuisine.cusine|slugify }}" class="tab-pane{% if forloop.first %} active{% endif %}">
            {% for menu in menus %}
                {% if menu.cuisineid == cuisine.cuisineid %}
                    <p>{{ menu.cusineid }}</p>
                    <div class="menu-item">
                        <div class="menu-item-name">{{ menu.name }}</div>
                        <div class="menu-item-description">{{ menu.description }}</div>
                        <div class="menu-item-price">£{{ menu.price }}</div>
                    </div>
                {% endif %}
            {% endfor %}
        </section>
    {% endfor %}
</div>

ChefsTable_control/templates/menu.html
{% extends 'base.html' %}

{% block content %}

<head>
    <link rel="stylesheet" href="//assets-cdn-refresh.getbento.com/stylesheet/highstdeli/1/scss/main.7ef889070d08c23869316b42bc890d92.scss">
    <style>
        /* Style for menu items */
        .menu-item {
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 5px;
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }

        .menu-item-name {
            font-weight: bold;
            font-size: 18px;
        }

        .menu-item-description {
            font-size: 16px;
            color: #555;
            margin-top: 5px;
        }

        .menu-item-price {
            font-size: 18px;
            font-weight: bold;
        }
        .vertical-tabs {
            display: flex;
            flex-direction: column;
            }
    </style>
</head>
<section id="menus" aria-label="menus-section" class="content revealable">
    <div class="tabs">
        <ul class="tabs-nav" role="tablist">
            {% for cuisine in cuisines %}
                <li role="presentation">
                    <a id="tab-{{ cuisine.cusine|slugify }}"
                        class="btn btn-tabs{% if forloop.first %} active{% endif %}"
                        href="#{{ cuisine.cusine|slugify }}"
                        role="tab"
                        aria-controls="{{ cuisine.cusine|slugify }}"
                        aria-selected="{% if forloop.first %}true{% else %}false{% endif %}"
                        data-order="{{ forloop.counter }}"
                        tabindex="{% if forloop.first %}0{% endif %}">
                        {{ cuisine.cusine }}
                    </a>
                    <ul>
                        {% for menu in cuisine.menu_set.all %}
                        <div class="menu-item">
                            <div class="menu-item-name">{{ menu.name }}</div>
                            <div class="menu-item-description">{{ menu.description }}</div>
                            <div class="menu-item-price">£{{ menu.price }}</div>
                        </div>
                        {% endfor %}
                        </ul>
                {% endfor %}
            </ul>
                </li>
                <script>
                    var tabs = document.querySelectorAll('.tabs-nav a');
            
                    for (var i = 0; i < tabs.length; i++) {
                        tabs[i].addEventListener('click', function(event) {
                            event.preventDefault();
            
                            var tab = event.target;
                            var activeTab = document.querySelector('.tabs-nav a.active');
                            var activeSection = document.querySelector('.tabs-content section.active');
            
                            if (tab === activeTab) {
                                return;
                            }
            
                            activeTab.classList.remove('active');
                            tab.classList.add('active');
            
                            activeSection.classList.remove('active');
                            var sectionId = tab.getAttribute('href').slice(1);
                            var section = document.getElementById(sectionId);
                            section.classList.add('active');
                        });
                    }
                </script>
        
    </div>
    


{% endblock %}

ChefsTable_control/templates/menu2.html
<head>
    <link rel="stylesheet" href="//assets-cdn-refresh.getbento.com/stylesheet/highstdeli/1/scss/main.7ef889070d08c23869316b42bc890d92.scss">
    <style>
        /* Style for menu items */
        .menu-item {
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 5px;
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }

        .menu-item-name {
            font-weight: bold;
            font-size: 18px;
        }

        .menu-item-description {
            font-size: 16px;
            color: #555;
            margin-top: 5px;
        }

        .menu-item-price {
            font-size: 18px;
            font-weight: bold;
        }
        .vertical-tabs {
            display: flex;
            flex-direction: column;
            }
    </style>
</head>

<section id="menus" aria-label="menus-section" class="content revealable">
    <div class="tabs">
        <ul class="tabs-nav" role="tablist">
            {% for cuisine in cuisines %}
                <li role="presentation">
                    <a id="tab-{{ cuisine.cusine|slugify }}"
                        class="btn btn-tabs{% if forloop.first %} active{% endif %}"
                        href="#{{ cuisine.cusine|slugify }}"
                        role="tab"
                        aria-controls="{{ cuisine.cusine|slugify }}"
                        aria-selected="{% if forloop.first %}true{% else %}false{% endif %}"
                        data-order="{{ forloop.counter }}"
                        tabindex="{% if forloop.first %}0{% endif %}">
                        {{ cuisine.cusine }}
                        
                    </a>
                {% endfor %}
            </ul>
                </li>
                <div class="tabs-content">
                    {% for cuisine in cuisines %}
                        <section id="{{ cuisine.cusine|slugify }}" role="tabpanel" aria-labelledby="tab-{{ cuisine.cusine|slugify }}" class="tab-pane{% if forloop.first %} active{% endif %}">
                            {% for menu in menus %}
                                {% if menu.cuisineid == cuisine.cuisineid %}
                                    <p>{{ menu.cusineid }}</p>
                                    <div class="menu-item">
                                        <div class="menu-item-name">{{ menu.name }}</div>
                                        <div class="menu-item-description">{{ menu.description }}</div>
                                        <div class="menu-item-price">£{{ menu.price }}</div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </section>
                    {% endfor %}
                </div>
        
    </div>
    <script>
        var tabs = document.querySelectorAll('.tabs-nav a');

        for (var i = 0; i < tabs.length; i++) {
            tabs[i].addEventListener('click', function(event) {
                event.preventDefault();

                var tab = event.target;
                var activeTab = document.querySelector('.tabs-nav a.active');
                var activeSection = document.querySelector('.tabs-content section.active');

                if (tab === activeTab) {
                    return;
                }

                activeTab.classList.remove('active');
                tab.classList.add('active');

                activeSection.classList.remove('active');
                var sectionId = tab.getAttribute('href').slice(1);
                var section = document.getElementById(sectionId);
                section.classList.add('active');
            });
        }
    </script>
</section>

ChefsTable_control/templates/menu3.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="menu-wrapper">
    {% for cuisine in cuisines %}
      <div class="cuisine-wrapper">
        <h2>{{ cuisine.cusine }}</h2>
        <div class="menu-items-wrapper">
          {% for menu in cuisine.menu_set.all %}
            <div class="menu-item">
              <h3>{{ menu.name }}</h3>
              <p>{{ menu.description }}</p>
              <span class="price">£{{ menu.price }}</span>
            </div>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

ChefsTable_control/templates/partials/footer.html
{% load static %}

<footer>
    <article>
        <img src="{% static 'images/banner2.png' %}"/>
    </article>
    <article>
        <p>Copyright ChefsTable</p>
    </article>
</footer>

ChefsTable_control/templates/partials/header.html
{% load static %}

<header>
  <img src="{% static 'images/banner.png' %}" />
</header>
<nav>
  <ul>
    <li><a href="{% url 'home' %} " style="font-size:x-large;">Home</a></li>
    <li><a href="{% url 'about' %}" style="font-size:x-large;">About</a></li>
    <li><a href="{% url 'menu' %}" style="font-size:x-large;">Menu</a></li>
    <li><a href="{% url 'booking' %}" style="font-size:x-large;">Book</a></li>
  </ul>
</nav>

ChefsTable_control/templates/sucessbook.html
{% extends 'base.html' %}

{% block content %}
<style>
    intro {
    width: 100%;
    float: left;
    padding: 100px 0;
    background: url('../images/AMB-Web-Pattern.jpg') no-repeat;
    background-size: cover;
    background-position: bottom;
    position: relative;
    color: #fff;
    text-align: center;
    }
</style>

<section class="intro">

    <div class="container">
  
      <div class="row">
  
        <div class="col-xs-12">
  
          <h2>  Reservation Success, See you at the restaurant !! </h2>
  
  
        <!-- end col-12 --> 
  
      </div>
  
      <!-- end row --> 
  
    </div>
  
    <!-- end container --> 
  
  </section>


{% endblock %}